// src/systems/audio/mod.rs
// Audio system: generates procedural sound effects on the fly.
// No audio files required — all sounds are synthesised from raw samples.

use rodio::source::Source;
use rodio::{OutputStream, OutputStreamHandle, Sink};
use std::time::Duration;

/// Sound effect kinds. Each generates a different procedural waveform.
#[derive(Debug, Clone, Copy)]
pub enum SoundEffect {
    Footstep,
    Hit,
    LevelTransition,
    DeathSting,
    Pickup,
}

/// AudioSystem owns a rodio output stream and active sound sinks.
pub struct AudioSystem {
    _stream: OutputStream,
    stream_handle: OutputStreamHandle,
    ambient_sink: Option<Sink>,
    last_movement_mag: f32,
}

impl AudioSystem {
    pub fn new() -> Option<Self> {
        let (stream, stream_handle) = OutputStream::try_default().ok()?;
        Some(Self {
            _stream: stream,
            stream_handle,
            ambient_sink: None,
            last_movement_mag: 0.0,
        })
    }

    /// Start the ambient drone loop. Idempotent.
    pub fn start_ambient(&mut self) {
        if self.ambient_sink.is_some() {
            return;
        }
        let sink = Sink::try_new(&self.stream_handle).ok();
        if let Some(s) = sink {
            s.append(AmbientDrone::new(44100));
            s.set_volume(0.18);
            self.ambient_sink = Some(s);
        }
    }

    pub fn pause_ambient(&self) {
        if let Some(sink) = self.ambient_sink.as_ref() {
            sink.pause();
        }
    }

    pub fn resume_ambient(&self) {
        if let Some(sink) = self.ambient_sink.as_ref() {
            sink.play();
        }
    }

    /// One-shot effect: play a short procedural sound.
    pub fn play(&self, effect: SoundEffect) {
        let Ok(sink) = Sink::try_new(&self.stream_handle) else {
            return;
        };
        let source: OneShot = match effect {
            SoundEffect::Footstep => OneShot::new(0.12, 0.5, footstep_wave, 44100),
            SoundEffect::Hit => OneShot::new(0.08, 0.4, hit_wave, 44100),
            SoundEffect::LevelTransition => OneShot::new(0.45, 0.35, whoosh_wave, 44100),
            SoundEffect::DeathSting => OneShot::new(0.6, 0.5, death_wave, 44100),
            SoundEffect::Pickup => OneShot::new(0.2, 0.4, pickup_wave, 44100),
        };
        sink.append(source);
        sink.detach();
    }

    /// Tick the footstep system.
    pub fn tick_footsteps(&mut self, _dt: f32, movement_mag: f32, _is_sprinting: bool) {
        const STEP_THRESHOLD: f32 = 0.5;
        if movement_mag > STEP_THRESHOLD && self.last_movement_mag <= STEP_THRESHOLD {
            self.play(SoundEffect::Footstep);
        }
        self.last_movement_mag = movement_mag;
    }
}

// ── Waveform functions ───────────────────────────────────────────────────────

fn footstep_wave(t: f32) -> f32 {
    let env = (-12.0 * t).exp();
    let noise = (t * 600.0).sin() * 0.3 + (t * 80.0).sin();
    env * noise * 0.5
}
fn hit_wave(t: f32) -> f32 {
    let env = (-30.0 * t).exp();
    let tone = (t * 1200.0).sin() + (t * 2400.0).sin() * 0.3;
    env * tone * 0.4
}
fn whoosh_wave(t: f32) -> f32 {
    let env = (-3.0 * t).exp() * (1.0 - (-2.0 * t).exp());
    let pitch = 200.0 + 600.0 * (-8.0 * (t - 0.15)).exp();
    let tone = (t * pitch).sin();
    let noise = (t * 2000.0).sin() * 0.5 + (t * 3500.0).sin() * 0.5;
    env * (tone * 0.6 + noise * 0.4) * 0.35
}
fn death_wave(t: f32) -> f32 {
    let env = (-2.0 * t).exp();
    let freq = 200.0 - 150.0 * t;
    (t * freq).sin() * env * 0.5
}
fn pickup_wave(t: f32) -> f32 {
    let env = (-4.0 * t).exp();
    let tone = (t * 600.0).sin() + (t * 900.0).sin() * 0.5;
    env * tone * 0.35
}

// ── One-shot procedural source ───────────────────────────────────────────────

/// Iterates through samples generated by a custom waveform function.
pub struct OneShot {
    sample_rate: u32,
    total_samples: u32,
    sample_idx: u32,
    volume: f32,
    wave_fn: Box<dyn Fn(f32) -> f32 + Send + Sync>,
}

impl OneShot {
    pub fn new(duration_s: f32, volume: f32, wave_fn: fn(f32) -> f32, sample_rate: u32) -> Self {
        Self {
            sample_rate,
            total_samples: (duration_s * sample_rate as f32) as u32 * 2, // stereo frames * 2
            sample_idx: 0,
            volume,
            wave_fn: Box::new(wave_fn),
        }
    }
}

impl Iterator for OneShot {
    type Item = f32;
    fn next(&mut self) -> Option<Self::Item> {
        if self.sample_idx >= self.total_samples {
            return None;
        }
        let t = (self.sample_idx / 2) as f32 / self.sample_rate as f32;
        let s = (self.wave_fn)(t) * self.volume;
        self.sample_idx += 1;
        Some(s)
    }
}

impl Source for OneShot {
    fn current_frame_len(&self) -> Option<usize> {
        Some(self.total_samples.saturating_sub(self.sample_idx) as usize)
    }
    fn channels(&self) -> u16 {
        2
    }
    fn sample_rate(&self) -> u32 {
        self.sample_rate
    }
    fn total_duration(&self) -> Option<Duration> {
        Some(Duration::from_secs_f32(
            self.total_samples as f32 / 2.0 / self.sample_rate as f32,
        ))
    }
}

// ── Ambient drone (looped) ────────────────────────────────────────────────────

pub struct AmbientDrone {
    sample_rate: u32,
    sample_idx: u64,
    channels: u16,
}

impl AmbientDrone {
    pub fn new(sample_rate: u32) -> Self {
        Self {
            sample_rate,
            sample_idx: 0,
            channels: 2,
        }
    }
}

impl Iterator for AmbientDrone {
    type Item = f32;
    fn next(&mut self) -> Option<Self::Item> {
        let t = self.sample_idx as f32 / self.sample_rate as f32;
        let drone = (t * 55.0).sin() * 0.5 + (t * 55.3).sin() * 0.5;
        let tremolo = 0.5 + 0.5 * (t * 0.3).sin();
        self.sample_idx = self.sample_idx.wrapping_add(1);
        Some(drone * tremolo * 0.25)
    }
}

impl Source for AmbientDrone {
    fn current_frame_len(&self) -> Option<usize> {
        None
    }
    fn channels(&self) -> u16 {
        self.channels
    }
    fn sample_rate(&self) -> u32 {
        self.sample_rate
    }
    fn total_duration(&self) -> Option<Duration> {
        None
    }
}
