"""Generate Cenotaph's intentionally neutral primitive placeholder kit.

Every runtime placeholder is exactly one geometric primitive. These files exist
only to expose scale, collision, color, motion, and gameplay role while real art
direction is unresolved. The generator must not invent anatomy or ornament.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class Mesh:
    def __init__(self, name: str):
        self.name = name
        self.vertices: list[tuple[float, float, float]] = []
        self.faces: list[tuple[int, int, int]] = []

    def set_primitive(self, vertices, faces):
        if self.vertices or self.faces:
            raise RuntimeError(f"{self.name} attempted to combine multiple primitives")
        self.vertices.extend(vertices)
        self.faces.extend(faces)

    def box(self, size):
        width, height, depth = size
        hx = width * 0.5
        hz = depth * 0.5
        self.set_primitive(
            [
                (-hx, 0.0, -hz),
                (hx, 0.0, -hz),
                (hx, 0.0, hz),
                (-hx, 0.0, hz),
                (-hx, height, -hz),
                (hx, height, -hz),
                (hx, height, hz),
                (-hx, height, hz),
            ],
            [
                (0, 2, 1), (0, 3, 2),
                (4, 5, 6), (4, 6, 7),
                (0, 1, 5), (0, 5, 4),
                (1, 2, 6), (1, 6, 5),
                (2, 3, 7), (2, 7, 6),
                (3, 0, 4), (3, 4, 7),
            ],
        )

    def frustum(self, bottom, top, height):
        bx, bz = bottom
        tx, tz = top
        self.set_primitive(
            [
                (-bx, 0.0, -bz),
                (bx, 0.0, -bz),
                (bx, 0.0, bz),
                (-bx, 0.0, bz),
                (-tx, height, -tz),
                (tx, height, -tz),
                (tx, height, tz),
                (-tx, height, tz),
            ],
            [
                (0, 2, 1), (0, 3, 2),
                (4, 5, 6), (4, 6, 7),
                (0, 1, 5), (0, 5, 4),
                (1, 2, 6), (1, 6, 5),
                (2, 3, 7), (2, 7, 6),
                (3, 0, 4), (3, 4, 7),
            ],
        )

    def octahedron(self, radii):
        rx, ry, rz = radii
        cy = ry
        self.set_primitive(
            [
                (0.0, cy + ry, 0.0),
                (rx, cy, 0.0),
                (0.0, cy, rz),
                (-rx, cy, 0.0),
                (0.0, cy, -rz),
                (0.0, 0.0, 0.0),
            ],
            [
                (0, 1, 2), (0, 2, 3), (0, 3, 4), (0, 4, 1),
                (5, 2, 1), (5, 3, 2), (5, 4, 3), (5, 1, 4),
            ],
        )

    def write(self, relative_path: str):
        path = ROOT / "assets" / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "# Intentionally neutral primitive placeholder",
            "# Generated by scripts/generate_prototype_models.py",
            f"o {self.name}",
        ]
        lines.extend(f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in self.vertices)
        lines.extend(
            f"vt {x * 0.37 + z * 0.13:.6f} {y * 0.31 - z * 0.09:.6f}"
            for x, y, z in self.vertices
        )
        lines.extend(
            f"f {a + 1}/{a + 1} {b + 1}/{b + 1} {c + 1}/{c + 1}"
            for a, b, c in self.faces
        )
        path.write_text("\n".join(lines) + "\n", encoding="ascii")


MODEL_SPECS = {
    "enemies/ashbound.obj": ("box", (0.60, 1.80, 0.50)),
    "enemies/burdened.obj": ("box", (1.35, 1.80, 1.00)),
    "enemies/censer.obj": ("octahedron", (0.36, 0.95, 0.36)),
    "enemies/chainrunner.obj": ("box", (0.90, 1.40, 0.55)),
    "enemies/harpy.obj": ("box", (2.70, 1.00, 0.45)),
    "pickups/resource_shard.obj": ("octahedron", (0.28, 0.62, 0.28)),
    "pickups/relic_ash_splinter.obj": ("octahedron", (0.22, 0.65, 0.22)),
    "pickups/relic_veil_cinder.obj": ("octahedron", (0.38, 0.50, 0.16)),
    "pickups/relic_chain_sigil.obj": ("octahedron", (0.40, 0.50, 0.18)),
    "props/test_obelisk.obj": ("frustum", ((0.45, 0.45), (0.28, 0.28), 2.00)),
    "props/test_platform.obj": ("box", (2.00, 0.30, 2.00)),
    "props/test_wall.obj": ("box", (1.00, 1.00, 1.00)),
    "world/anchor_marker.obj": ("octahedron", (0.55, 1.00, 0.55)),
    "world/hurtbox_warning.obj": ("octahedron", (0.70, 0.70, 0.70)),
    "world/transition_gate.obj": ("box", (1.50, 2.20, 0.45)),
}


def main():
    for relative_path, (primitive, arguments) in MODEL_SPECS.items():
        mesh = Mesh(Path(relative_path).stem)
        if primitive == "frustum":
            mesh.frustum(*arguments)
        else:
            getattr(mesh, primitive)(arguments)
        if not mesh.vertices or not mesh.faces:
            raise RuntimeError(f"{relative_path} generated empty geometry")
        mesh.write(relative_path)
        print(
            f"generated {relative_path}: {primitive}, "
            f"{len(mesh.vertices)} vertices, {len(mesh.faces)} triangles"
        )


if __name__ == "__main__":
    main()
